### PR TITLE
removing the ignored files since they are not needed any more

### PR DESCRIPTION
**Pull request by nlyubova**
@mikaelarguedas do you agree to remove them now?

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
absolutely +1

**Comment by mikaelarguedas** [comment]
@nlyubova but I do think that `romeo_dcm_control` should stay in this repo, be called `romeo_control` and be released as part of romeo_robot (given that nothing in `romeo_dcm_control` depends on DCM). This would avoid creating a gbp for `romeo_dcm` because all the DCM specific packages cannot be released on the buildfarm. This would also allow consistency accross the different Aldeb robots

**Comment by mikaelarguedas** [comment]
@nlyubova I think that the discussion should happen here and not on rosdistro. Agreed that `romeo_control` it's not DCM/naoqi dependent, that's my argument to keep it out of the romeo_dcm repo and never releasing `romeo_dcm` that is looking for the naoqi c++ sdk at configure time.
I think that a romeo_virtual containing the controllers + the gazebo plugin as for Nao and Pepper would be better. I can handle the git moving/merging repos if you want.

**Comment by mikaelarguedas** [comment]
deleting this branch given that it has been merged

**Comment by mikaelarguedas** [comment]
@nlyubova I didn't hear back from you, so I went forward because time appeared to be of the essence. I created [the repo](https://github.com/ros-aldebaran/romeo_virtual) and moved rename the packages accordingly to the other robots. Would you be able to test them on Indigo before I release them? Most of the roboticsgroup code don't compile on kinetic. I fixed only what was necessary to spawn a robot in gazebo7 and be sure that the controllers are working. but I would like your input to be sure it does the same thing as your previous one on indigo.
The [release repo](https://github.com/ros-aldebaran/romeo_virtual-release) has been and I updated changelogs and version so that you can run `bloom-release` directly once it's tested and validated.

BTW: [this file](https://github.com/ros-aldebaran/romeo_virtual/blob/master/romeo_gazebo_plugin/launch/romeo_gazebo.launch#L17) seems to be missing

**Comment by nlyubova** [comment]
Hi Mikael, thank you. I've fixed the launch file, YAML is not needed because PID are not public. please do not do changes, I need this repop as it is (or working for Gazebo2) for few days. And I will not have much internet

**Comment by mikaelarguedas** [comment]
@nlyubova I didn't change anything upstream. I wanted you to test it because I never tested this package before and didn't know what to expect (e.g. broken launchfile, missing PIDs etc). If the current status of upstream matches what you want to release I can release it right now.

**Comment by nlyubova** [comment]
@mikaelarguedas I've seen that you've released it. . After changing a project name you should get few broken launch/config files. But I do not have much internet for few days, so I will test it once I can

**Pull request merged**
